sine:
        DB             128 
        DB             131 
        DB             134 
        DB             137 
        DB             141 
        DB             144 
        DB             147 
        DB             150 
        DB             153 
        DB             156 
        DB             159 
        DB             162 
        DB             165 
        DB             168 
        DB             171 
        DB             173 
        DB             176 
        DB             179 
        DB             182 
        DB             184 
        DB             187 
        DB             189 
        DB             192 
        DB             194 
        DB             196 
        DB             199 
        DB             201 
        DB             203 
        DB             205 
        DB             207 
        DB             209 
        DB             211 
        DB             212 
        DB             214 
        DB             216 
        DB             217 
        DB             218 
        DB             220 
        DB             221 
        DB             222 
        DB             223 
        DB             224 
        DB             225 
        DB             226 
        DB             226 
        DB             227 
        DB             227 
        DB             228 
        DB             228 
        DB             228 
        DB             228 
        DB             228 
        DB             228 
        DB             228 
        DB             227 
        DB             227 
        DB             226 
        DB             226 
        DB             225 
        DB             224 
        DB             223 
        DB             222 
        DB             221 
        DB             220 
        DB             218 
        DB             217 
        DB             216 
        DB             214 
        DB             212 
        DB             211 
        DB             209 
        DB             207 
        DB             205 
        DB             203 
        DB             201 
        DB             199 
        DB             196 
        DB             194 
        DB             192 
        DB             189 
        DB             187 
        DB             184 
        DB             182 
        DB             179 
        DB             176 
        DB             173 
        DB             171 
        DB             168 
        DB             165 
        DB             162 
        DB             159 
        DB             156 
        DB             153 
        DB             150 
        DB             147 
        DB             144 
        DB             141 
        DB             137 
        DB             134 
        DB             131 
        DB             128 
        DB             125 
        DB             122 
        DB             119 
        DB             115 
        DB             112 
        DB             109 
        DB             106 
        DB             103 
        DB             100 
        DB             97 
        DB             94 
        DB             91 
        DB             88 
        DB             85 
        DB             83 
        DB             80 
        DB             77 
        DB             74 
        DB             72 
        DB             69 
        DB             67 
        DB             64 
        DB             62 
        DB             60 
        DB             57 
        DB             55 
        DB             53 
        DB             51 
        DB             49 
        DB             47 
        DB             45 
        DB             44 
        DB             42 
        DB             40 
        DB             39 
        DB             38 
        DB             36 
        DB             35 
        DB             34 
        DB             33 
        DB             32 
        DB             31 
        DB             30 
        DB             30 
        DB             29 
        DB             29 
        DB             28 
        DB             28 
        DB             28 
        DB             28 
        DB             28 
        DB             28 
        DB             28 
        DB             29 
        DB             29 
        DB             30 
        DB             30 
        DB             31 
        DB             32 
        DB             33 
        DB             34 
        DB             35 
        DB             36 
        DB             38 
        DB             39 
        DB             40 
        DB             42 
        DB             44 
        DB             45 
        DB             47 
        DB             49 
        DB             51 
        DB             53 
        DB             55 
        DB             57 
        DB             60 
        DB             62 
        DB             64 
        DB             67 
        DB             69 
        DB             72 
        DB             74 
        DB             77 
        DB             80 
        DB             83 
        DB             85 
        DB             88 
        DB             91 
        DB             94 
        DB             97 
        DB             100 
        DB             103 
        DB             106 
        DB             109 
        DB             111 
        DB             114 
        DB             117 
        DB             120 
        DB             124 
		DB             128